version: '3.9'

services:
  db:
    container_name: 'pg_db'
    image: 'postgres:14-alpine'
    restart: 'always'
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_DB
      POSTGRES_PORT: $DATABASE_PORT
    volumes:
      - './postgres_data:/var/lib/postgresql/data/'
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'

#  pgadmin:
#    container_name: 'pgadmin'
#    image: 'dpage/pgadmin4'
#    environment:
#      PGADMIN_DEFAULT_EMAIL: 'noemail@noemail.com'
#      PGADMIN_DEFAULT_PASSWORD: 'root'
#    ports:
#      - '5050:80'
#
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080